stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/a1_RestaurantReviews_HistoricDump.csv
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/a1_RestaurantReviews_HistoricDump.csv
    - src/preprocess.py
    outs:
    - data/X.npy
    - data/y.npy
    - ml_models/preproccesing_object.pkl
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/X.npy
    - data/y.npy
    - src/train_model.py
    outs:
    - ml_models/c2_Classifier_Sentiment_Model
