stages:
  get_data:
    cmd: python src/data/get_data.py
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/a1_RestaurantReviews_HistoricDump.csv
  preprocess:
    cmd: python src/features/preprocess.py
    deps:
    - data/raw/a1_RestaurantReviews_HistoricDump.csv
    - src/features/preprocess.py
    outs:
    - data/processed/X.npy
    - data/processed/y.npy
    - ml_models/preproccesing_object.pkl
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/X.npy
    - data/processed/y.npy
    - src/models/train_model.py
    outs:
    - ml_models/c2_Classifier_Sentiment_Model
    metrics:
    - ml_models/metrics/metrics.json:
        cache: false
